### PR TITLE
Hosted composer packages available via v2 api

### LINKED ISSUE #116: Hosted composer packages that were published before update are not available via v2 api
### What are you trying to do?

Having:
  * An instance running with plugin 0.0.18
  * Published packages in a hosted composer repo
  * Have them working with composer v1 api

Then:
  * Upgrade plugin from 0.0.18 to 0.0.22
  * In the same step upgrade Nexus from 3.37.3-02 to 3.38.0-01 (probably irrelevant)
  * Try to download packages via composer v2 api

### What feature or behavior is this required for?

Downloading packages via composer v2 api

### How could we solve this issue? (Not knowing is okay!)

It seems that Nexus is only creating the package metadata when the packages are published.
Even though that seems to be the case, I have inconsistent behavior between a hosted instance and the docker container I can create with this repo.
In the docker container republishing the same version of a package seems to trigger the creation of v2 metadata.
In the hosted instance it does not.

In both versions I can delete a version package and publish it again afterwards and the v2 metadata is created.
This is not a suitable workaround though.

I would recon, that re-indexing the packages should trigger the creation of the v2 metadata, BUT:

  1. I am not sure about that
  
  2. It does not seem to work, because of this:

     ```
     2022-06-24 11:06:42,804+0200 ERROR [quartz-12-thread-15]  *SYSTEM org.sonatype.nexus.repository.content.search.SearchFacetImpl - Unable to rebuild search index for repository composer-internal org.sonatype.nexus.repository.MissingFacetException: No facet of type ContentFacet attached to repository composer-internal
     at org.sonatype.nexus.repository.manager.internal.RepositoryImpl.facet(RepositoryImpl.java:322)
     at org.sonatype.nexus.repository.content.search.SearchFacetImpl.rebuildComponentIndex(SearchFacetImpl.java:154)
     at org.sonatype.nexus.repository.content.search.SearchFacetImpl.rebuildIndex(SearchFacetImpl.java:145)
     at org.sonatype.nexus.repository.content.search.SearchFacetImpl$$EnhancerByGuice$$421846345.GUICE$TRAMPOLINE(<generated>)
     at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:74)
     at org.sonatype.nexus.common.stateguard.MethodInvocationAction.run(MethodInvocationAction.java:39)
     at org.sonatype.nexus.common.stateguard.StateGuard$GuardImpl.run(StateGuard.java:272)
     at org.sonatype.nexus.common.stateguard.GuardedInterceptor.invoke(GuardedInterceptor.java:54)
     at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:75)
     at com.google.inject.internal.InterceptorStackCallback.invoke(InterceptorStackCallback.java:55)
     at org.sonatype.nexus.repository.content.search.SearchFacetImpl$$EnhancerByGuice$$421846345.rebuildIndex(<generated>)
     at org.sonatype.nexus.repository.search.index.RebuildIndexTask.execute(RebuildIndexTask.java:33)
     at org.sonatype.nexus.repository.RepositoryTaskSupport.execute(RepositoryTaskSupport.java:79)
     at org.sonatype.nexus.scheduling.TaskSupport.call(TaskSupport.java:100)
     at org.sonatype.nexus.quartz.internal.task.QuartzTaskJob.doExecute(QuartzTaskJob.java:143)
     at org.sonatype.nexus.quartz.internal.task.QuartzTaskJob.execute(QuartzTaskJob.java:106)
     at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
     at org.sonatype.nexus.quartz.internal.QuartzThreadPool.lambda$0(QuartzThreadPool.java:145)
     at org.sonatype.nexus.thread.internal.MDCAwareRunnable.run(MDCAwareRunnable.java:40)
     at org.apache.shiro.subject.support.SubjectRunnable.doRun(SubjectRunnable.java:120)
     at org.apache.shiro.subject.support.SubjectRunnable.run(SubjectRunnable.java:108)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     at java.lang.Thread.run(Thread.java:748)
     ```

### Anything else?

Nope

### PR DESCRIPTION
**Pull request by Locco123456**
This pull request makes the following changes:
* If content with PackagePath == null, check ProviderPath

It relates to the following issue:
* Fixes #116

### CODE REVIEW

File: nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerHostedFacetImpl.java [hunk 1]
```diff
@@ -84,7 +84,8 @@ public Content getProviderJson(final String vendor, final String project) throws
   @Override
   @TransactionalTouchMetadata
   public Content getPackageJson(final String vendor, final String project) throws IOException {
-    return content().get(ComposerPathUtils.buildPackagePath(vendor, project));
+    Content content = content().get(ComposerPathUtils.buildPackagePath(vendor, project));
+    return content != null ? content : content().get(ComposerPathUtils.buildProviderPath(vendor, project));
```
Comment (func0der) [inline nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerHostedFacetImpl.java:88]: should we add a comment to signal that this is compatibility layer to support composer v1 packages?

File: nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerProxyFacetImpl.java [hunk 2]
```diff
@@ -162,7 +162,7 @@ protected CacheController getCacheController(@Nonnull final Context context) {
     return cacheControllerHolder.require(assetKind.getCacheType());
   }
 
-  private Content generatePackagesJson(final Context context) throws IOException {
```
Comment (func0der) [inline nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerProxyFacetImpl.java:165]: Why did this `throws` disappear?

File: nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerProxyFacetImpl.java [hunk 3]
```diff
@@ -203,7 +203,6 @@ private String getZipballUrl(final Context context) {
       try {
         String path = "/" + buildPackagePathForDevVersions(vendor, project);
         Payload payload = getPackagePayload(context, path);
-        String url = composerJsonProcessor.getDistUrlFromPackage(vendor, project, version, payload);
```
Comment (func0der) [inline nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerProxyFacetImpl.java:206]: was this maybe the only issue we had, because `payload` was not check beforehand or do we need the part with `package` and the `provider` path?

**Comment by user-8f93f49a** [comment]
@Locco123456, thanks so much for your efforts and dedication on this fix.
With your fix, we were able to use composer v2.

So If you could have some time, could you please check the comments?
I'm delighted awaiting your pull request to be merged there :)

Thanks and Warm Regards!

File: nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerProxyFacetImpl.java (hunk 2 above)
Comment (Locco123456) [reply nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerProxyFacetImpl.java:165]: It was unused

File: nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerHostedFacetImpl.java (hunk 1 above)
Comment (Locco123456) [reply nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerHostedFacetImpl.java:88]: I will leave a comment there.

File: nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerProxyFacetImpl.java (hunk 3 above)
Comment (Locco123456) [reply nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerProxyFacetImpl.java:206]: Just some cleanup...

**Review by func0der — APPROVED** [review]

**Review by func0der — APPROVED** [review]

**Comment by func0der** [comment]
@bhamail Could you check on circle/ci and on merging this PR, please?

**Review by bhamail — APPROVED** [review]
LGTM, but I'm no expert. Please be sure to test these changes yourself, as I've only verified the CI build is happy. I'll merge shortly.
Thanks for the fix!
